# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License version 3"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://www.curseforge.com/minecraft/mc-addons/desert-improved-survival/issues" #optional
[[mods]]
modId="desertsurvival"
version="0.2"
displayName="Desert Survival"
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/TechniMan/desert-survival/blob/main/modver.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-addons/desert-improved-survival" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="desertsurvival.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Will Thomas <techniman>" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A simple mod to aid surviving in desert biomes.

Adds recipes to make dirt and saplings using resources found in the desert biome, and a way to turn cacti into food.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
